
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* These values define the type of firmware release.  These values indicate the first version or release of this type.  For example the first alpha release would be 64, the second would be 65.
*/
public class FIRMWARE_VERSION_TYPE {
   public static final int FIRMWARE_VERSION_TYPE_DEV = 0; /* development release | */
   public static final int FIRMWARE_VERSION_TYPE_ALPHA = 64; /* alpha release | */
   public static final int FIRMWARE_VERSION_TYPE_BETA = 128; /* beta release | */
   public static final int FIRMWARE_VERSION_TYPE_RC = 192; /* release candidate | */
   public static final int FIRMWARE_VERSION_TYPE_OFFICIAL = 255; /* official stable release | */
   public static final int FIRMWARE_VERSION_TYPE_ENUM_END = 256; /*  | */
}
            