
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_PROTUNE_GAIN {
   public static final int GOPRO_PROTUNE_GAIN_400 = 0; /* ISO 400 | */
   public static final int GOPRO_PROTUNE_GAIN_800 = 1; /* ISO 800 (Only Hero 4) | */
   public static final int GOPRO_PROTUNE_GAIN_1600 = 2; /* ISO 1600 | */
   public static final int GOPRO_PROTUNE_GAIN_3200 = 3; /* ISO 3200 (Only Hero 4) | */
   public static final int GOPRO_PROTUNE_GAIN_6400 = 4; /* ISO 6400 | */
   public static final int GOPRO_PROTUNE_GAIN_ENUM_END = 5; /*  | */
}
            