
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_CAPTURE_MODE {
   public static final int GOPRO_CAPTURE_MODE_VIDEO = 0; /* Video mode | */
   public static final int GOPRO_CAPTURE_MODE_PHOTO = 1; /* Photo mode | */
   public static final int GOPRO_CAPTURE_MODE_BURST = 2; /* Burst mode, hero 3+ only | */
   public static final int GOPRO_CAPTURE_MODE_TIME_LAPSE = 3; /* Time lapse mode, hero 3+ only | */
   public static final int GOPRO_CAPTURE_MODE_MULTI_SHOT = 4; /* Multi shot mode, hero 4 only | */
   public static final int GOPRO_CAPTURE_MODE_PLAYBACK = 5; /* Playback mode, hero 4 only, silver only except when LCD or HDMI is connected to black | */
   public static final int GOPRO_CAPTURE_MODE_SETUP = 6; /* Playback mode, hero 4 only | */
   public static final int GOPRO_CAPTURE_MODE_UNKNOWN = 255; /* Mode not yet known | */
   public static final int GOPRO_CAPTURE_MODE_ENUM_END = 256; /*  | */
}
            