
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class FACTORY_TEST {
   public static final int FACTORY_TEST_AXIS_RANGE_LIMITS = 0; /* Tests to make sure each axis can move to its mechanical limits | */
   public static final int FACTORY_TEST_ENUM_END = 1; /*  | */
}
            