
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_VIDEO_SETTINGS_FLAGS {
   public static final int GOPRO_VIDEO_SETTINGS_TV_MODE = 1; /* 0=NTSC, 1=PAL | */
   public static final int GOPRO_VIDEO_SETTINGS_FLAGS_ENUM_END = 2; /*  | */
}
            