
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_FRAME_RATE {
   public static final int GOPRO_FRAME_RATE_12 = 0; /* 12 FPS | */
   public static final int GOPRO_FRAME_RATE_15 = 1; /* 15 FPS | */
   public static final int GOPRO_FRAME_RATE_24 = 2; /* 24 FPS | */
   public static final int GOPRO_FRAME_RATE_25 = 3; /* 25 FPS | */
   public static final int GOPRO_FRAME_RATE_30 = 4; /* 30 FPS | */
   public static final int GOPRO_FRAME_RATE_48 = 5; /* 48 FPS | */
   public static final int GOPRO_FRAME_RATE_50 = 6; /* 50 FPS | */
   public static final int GOPRO_FRAME_RATE_60 = 7; /* 60 FPS | */
   public static final int GOPRO_FRAME_RATE_80 = 8; /* 80 FPS | */
   public static final int GOPRO_FRAME_RATE_90 = 9; /* 90 FPS | */
   public static final int GOPRO_FRAME_RATE_100 = 10; /* 100 FPS | */
   public static final int GOPRO_FRAME_RATE_120 = 11; /* 120 FPS | */
   public static final int GOPRO_FRAME_RATE_240 = 12; /* 240 FPS | */
   public static final int GOPRO_FRAME_RATE_12_5 = 13; /* 12.5 FPS | */
   public static final int GOPRO_FRAME_RATE_ENUM_END = 14; /*  | */
}
            