
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_PROTUNE_COLOUR {
   public static final int GOPRO_PROTUNE_COLOUR_STANDARD = 0; /* Auto | */
   public static final int GOPRO_PROTUNE_COLOUR_NEUTRAL = 1; /* Neutral | */
   public static final int GOPRO_PROTUNE_COLOUR_ENUM_END = 2; /*  | */
}
            