
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_COMMAND {
   public static final int GOPRO_COMMAND_POWER = 0; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_CAPTURE_MODE = 1; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_SHUTTER = 2; /* (___/Set) | */
   public static final int GOPRO_COMMAND_BATTERY = 3; /* (Get/___) | */
   public static final int GOPRO_COMMAND_MODEL = 4; /* (Get/___) | */
   public static final int GOPRO_COMMAND_VIDEO_SETTINGS = 5; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_LOW_LIGHT = 6; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_PHOTO_RESOLUTION = 7; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_PHOTO_BURST_RATE = 8; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_PROTUNE = 9; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_PROTUNE_WHITE_BALANCE = 10; /* (Get/Set) Hero 3+ Only | */
   public static final int GOPRO_COMMAND_PROTUNE_COLOUR = 11; /* (Get/Set) Hero 3+ Only | */
   public static final int GOPRO_COMMAND_PROTUNE_GAIN = 12; /* (Get/Set) Hero 3+ Only | */
   public static final int GOPRO_COMMAND_PROTUNE_SHARPNESS = 13; /* (Get/Set) Hero 3+ Only | */
   public static final int GOPRO_COMMAND_PROTUNE_EXPOSURE = 14; /* (Get/Set) Hero 3+ Only | */
   public static final int GOPRO_COMMAND_TIME = 15; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_CHARGING = 16; /* (Get/Set) | */
   public static final int GOPRO_COMMAND_ENUM_END = 17; /*  | */
}
            