
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_BURST_RATE {
   public static final int GOPRO_BURST_RATE_3_IN_1_SECOND = 0; /* 3 Shots / 1 Second | */
   public static final int GOPRO_BURST_RATE_5_IN_1_SECOND = 1; /* 5 Shots / 1 Second | */
   public static final int GOPRO_BURST_RATE_10_IN_1_SECOND = 2; /* 10 Shots / 1 Second | */
   public static final int GOPRO_BURST_RATE_10_IN_2_SECOND = 3; /* 10 Shots / 2 Second | */
   public static final int GOPRO_BURST_RATE_10_IN_3_SECOND = 4; /* 10 Shots / 3 Second (Hero 4 Only) | */
   public static final int GOPRO_BURST_RATE_30_IN_1_SECOND = 5; /* 30 Shots / 1 Second | */
   public static final int GOPRO_BURST_RATE_30_IN_2_SECOND = 6; /* 30 Shots / 2 Second | */
   public static final int GOPRO_BURST_RATE_30_IN_3_SECOND = 7; /* 30 Shots / 3 Second | */
   public static final int GOPRO_BURST_RATE_30_IN_6_SECOND = 8; /* 30 Shots / 6 Second | */
   public static final int GOPRO_BURST_RATE_ENUM_END = 9; /*  | */
}
            