
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_FIELD_OF_VIEW {
   public static final int GOPRO_FIELD_OF_VIEW_WIDE = 0; /* 0x00: Wide | */
   public static final int GOPRO_FIELD_OF_VIEW_MEDIUM = 1; /* 0x01: Medium | */
   public static final int GOPRO_FIELD_OF_VIEW_NARROW = 2; /* 0x02: Narrow | */
   public static final int GOPRO_FIELD_OF_VIEW_ENUM_END = 3; /*  | */
}
            