
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_PROTUNE_WHITE_BALANCE {
   public static final int GOPRO_PROTUNE_WHITE_BALANCE_AUTO = 0; /* Auto | */
   public static final int GOPRO_PROTUNE_WHITE_BALANCE_3000K = 1; /* 3000K | */
   public static final int GOPRO_PROTUNE_WHITE_BALANCE_5500K = 2; /* 5500K | */
   public static final int GOPRO_PROTUNE_WHITE_BALANCE_6500K = 3; /* 6500K | */
   public static final int GOPRO_PROTUNE_WHITE_BALANCE_RAW = 4; /* Camera Raw | */
   public static final int GOPRO_PROTUNE_WHITE_BALANCE_ENUM_END = 5; /*  | */
}
            