
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_PHOTO_RESOLUTION {
   public static final int GOPRO_PHOTO_RESOLUTION_5MP_MEDIUM = 0; /* 5MP Medium | */
   public static final int GOPRO_PHOTO_RESOLUTION_7MP_MEDIUM = 1; /* 7MP Medium | */
   public static final int GOPRO_PHOTO_RESOLUTION_7MP_WIDE = 2; /* 7MP Wide | */
   public static final int GOPRO_PHOTO_RESOLUTION_10MP_WIDE = 3; /* 10MP Wide | */
   public static final int GOPRO_PHOTO_RESOLUTION_12MP_WIDE = 4; /* 12MP Wide | */
   public static final int GOPRO_PHOTO_RESOLUTION_ENUM_END = 5; /*  | */
}
            