
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class GOPRO_PROTUNE_EXPOSURE {
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_5_0 = 0; /* -5.0 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_4_5 = 1; /* -4.5 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_4_0 = 2; /* -4.0 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_3_5 = 3; /* -3.5 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_3_0 = 4; /* -3.0 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_2_5 = 5; /* -2.5 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_2_0 = 6; /* -2.0 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_1_5 = 7; /* -1.5 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_1_0 = 8; /* -1.0 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_NEG_0_5 = 9; /* -0.5 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_ZERO = 10; /* 0.0 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_0_5 = 11; /* +0.5 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_1_0 = 12; /* +1.0 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_1_5 = 13; /* +1.5 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_2_0 = 14; /* +2.0 EV | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_2_5 = 15; /* +2.5 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_3_0 = 16; /* +3.0 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_3_5 = 17; /* +3.5 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_4_0 = 18; /* +4.0 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_4_5 = 19; /* +4.5 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_POS_5_0 = 20; /* +5.0 EV (Hero 3+ Only) | */
   public static final int GOPRO_PROTUNE_EXPOSURE_ENUM_END = 21; /*  | */
}
            