
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class MAG_CAL_STATUS {
   public static final int MAG_CAL_NOT_STARTED = 0; /*  | */
   public static final int MAG_CAL_WAITING_TO_START = 1; /*  | */
   public static final int MAG_CAL_RUNNING_STEP_ONE = 2; /*  | */
   public static final int MAG_CAL_RUNNING_STEP_TWO = 3; /*  | */
   public static final int MAG_CAL_SUCCESS = 4; /*  | */
   public static final int MAG_CAL_FAILED = 5; /*  | */
   public static final int MAG_CAL_STATUS_ENUM_END = 6; /*  | */
}
            