
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* Specifies the datatype of a MAVLink parameter.
*/
public class MAV_PARAM_TYPE {
   public static final int MAV_PARAM_TYPE_UINT8 = 1; /* 8-bit unsigned integer | */
   public static final int MAV_PARAM_TYPE_INT8 = 2; /* 8-bit signed integer | */
   public static final int MAV_PARAM_TYPE_UINT16 = 3; /* 16-bit unsigned integer | */
   public static final int MAV_PARAM_TYPE_INT16 = 4; /* 16-bit signed integer | */
   public static final int MAV_PARAM_TYPE_UINT32 = 5; /* 32-bit unsigned integer | */
   public static final int MAV_PARAM_TYPE_INT32 = 6; /* 32-bit signed integer | */
   public static final int MAV_PARAM_TYPE_UINT64 = 7; /* 64-bit unsigned integer | */
   public static final int MAV_PARAM_TYPE_INT64 = 8; /* 64-bit signed integer | */
   public static final int MAV_PARAM_TYPE_REAL32 = 9; /* 32-bit floating-point | */
   public static final int MAV_PARAM_TYPE_REAL64 = 10; /* 64-bit floating-point | */
   public static final int MAV_PARAM_TYPE_ENUM_END = 11; /*  | */
}
            