
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class MAVLINK_DATA_STREAM_TYPE {
   public static final int MAVLINK_DATA_STREAM_IMG_JPEG = 1; /*  | */
   public static final int MAVLINK_DATA_STREAM_IMG_BMP = 2; /*  | */
   public static final int MAVLINK_DATA_STREAM_IMG_RAW8U = 3; /*  | */
   public static final int MAVLINK_DATA_STREAM_IMG_RAW32U = 4; /*  | */
   public static final int MAVLINK_DATA_STREAM_IMG_PGM = 5; /*  | */
   public static final int MAVLINK_DATA_STREAM_IMG_PNG = 6; /*  | */
   public static final int MAVLINK_DATA_STREAM_TYPE_ENUM_END = 7; /*  | */
}
            