
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* 
*/
public class PID_TUNING_AXIS {
   public static final int PID_TUNING_ROLL = 1; /*  | */
   public static final int PID_TUNING_PITCH = 2; /*  | */
   public static final int PID_TUNING_YAW = 3; /*  | */
   public static final int PID_TUNING_AXIS_ENUM_END = 4; /*  | */
}
            