
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
* SERIAL_CONTROL device types
*/
public class SERIAL_CONTROL_DEV {
   public static final int SERIAL_CONTROL_DEV_TELEM1 = 0; /* First telemetry port | */
   public static final int SERIAL_CONTROL_DEV_TELEM2 = 1; /* Second telemetry port | */
   public static final int SERIAL_CONTROL_DEV_GPS1 = 2; /* First GPS port | */
   public static final int SERIAL_CONTROL_DEV_GPS2 = 3; /* Second GPS port | */
   public static final int SERIAL_CONTROL_DEV_SHELL = 10; /* system shell | */
   public static final int SERIAL_CONTROL_DEV_ENUM_END = 11; /*  | */
}
            