/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */
         
// MESSAGE CAMERA_FEEDBACK PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Parser;
import com.MAVLink.ardupilotmega.CRC;
import java.nio.ByteBuffer;
import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

/**
* Camera Capture Feedback
*/
public class msg_camera_feedback_test{

public static final int MAVLINK_MSG_ID_CAMERA_FEEDBACK = 180;
public static final int MAVLINK_MSG_LENGTH = 45;
private static final long serialVersionUID = MAVLINK_MSG_ID_CAMERA_FEEDBACK;

private Parser parser = new Parser();

public CRC generateCRC(byte[] packet){
    CRC crc = new CRC();
    for (int i = 1; i < packet.length - 2; i++) {
        crc.update_checksum(packet[i] & 0xFF);
    }
    crc.finish_checksum(MAVLINK_MSG_ID_CAMERA_FEEDBACK);
    return crc;
}

public byte[] generateTestPacket(){
    ByteBuffer payload = ByteBuffer.allocate(6 + MAVLINK_MSG_LENGTH + 2);
    payload.put((byte)MAVLinkPacket.MAVLINK_STX); //stx
    payload.put((byte)MAVLINK_MSG_LENGTH); //len
    payload.put((byte)0); //seq
    payload.put((byte)255); //sysid
    payload.put((byte)190); //comp id
    payload.put((byte)MAVLINK_MSG_ID_CAMERA_FEEDBACK); //msg id
    payload.putLong((long)93372036854775807L); //time_usec
    payload.putInt((int)963497880); //lat
    payload.putInt((int)963498088); //lng
    payload.putFloat((float)129.0); //alt_msl
    payload.putFloat((float)157.0); //alt_rel
    payload.putFloat((float)185.0); //roll
    payload.putFloat((float)213.0); //pitch
    payload.putFloat((float)241.0); //yaw
    payload.putFloat((float)269.0); //foc_len
    payload.putShort((short)19315); //img_idx
    payload.put((byte)3); //target_system
    payload.put((byte)70); //cam_idx
    payload.put((byte)137); //flags
    
    CRC crc = generateCRC(payload.array());
    payload.put((byte)crc.getLSB());
    payload.put((byte)crc.getMSB());
    return payload.array();
}

@Test
public void test(){
    byte[] packet = generateTestPacket();
    for(int i = 0; i < packet.length - 1; i++){
        parser.mavlink_parse_char(packet[i] & 0xFF);
    }
    MAVLinkPacket m = parser.mavlink_parse_char(packet[packet.length - 1] & 0xFF);
    byte[] processedPacket = m.encodePacket();
    assertArrayEquals("msg_camera_feedback", processedPacket, packet);
}
}
        