/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */
         
// MESSAGE LED_CONTROL PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Parser;
import com.MAVLink.ardupilotmega.CRC;
import java.nio.ByteBuffer;
import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

/**
* Control vehicle LEDs
*/
public class msg_led_control_test{

public static final int MAVLINK_MSG_ID_LED_CONTROL = 186;
public static final int MAVLINK_MSG_LENGTH = 29;
private static final long serialVersionUID = MAVLINK_MSG_ID_LED_CONTROL;

private Parser parser = new Parser();

public CRC generateCRC(byte[] packet){
    CRC crc = new CRC();
    for (int i = 1; i < packet.length - 2; i++) {
        crc.update_checksum(packet[i] & 0xFF);
    }
    crc.finish_checksum(MAVLINK_MSG_ID_LED_CONTROL);
    return crc;
}

public byte[] generateTestPacket(){
    ByteBuffer payload = ByteBuffer.allocate(6 + MAVLINK_MSG_LENGTH + 2);
    payload.put((byte)MAVLinkPacket.MAVLINK_STX); //stx
    payload.put((byte)MAVLINK_MSG_LENGTH); //len
    payload.put((byte)0); //seq
    payload.put((byte)255); //sysid
    payload.put((byte)190); //comp id
    payload.put((byte)MAVLINK_MSG_ID_LED_CONTROL); //msg id
    payload.put((byte)5); //target_system
    payload.put((byte)72); //target_component
    payload.put((byte)139); //instance
    payload.put((byte)206); //pattern
    payload.put((byte)17); //custom_len
    //custom_bytes
    payload.put((byte)84);
    payload.put((byte)85);
    payload.put((byte)86);
    payload.put((byte)87);
    payload.put((byte)88);
    payload.put((byte)89);
    payload.put((byte)90);
    payload.put((byte)91);
    payload.put((byte)92);
    payload.put((byte)93);
    payload.put((byte)94);
    payload.put((byte)95);
    payload.put((byte)96);
    payload.put((byte)97);
    payload.put((byte)98);
    payload.put((byte)99);
    payload.put((byte)100);
    payload.put((byte)101);
    payload.put((byte)102);
    payload.put((byte)103);
    payload.put((byte)104);
    payload.put((byte)105);
    payload.put((byte)106);
    payload.put((byte)107);
    
    CRC crc = generateCRC(payload.array());
    payload.put((byte)crc.getLSB());
    payload.put((byte)crc.getMSB());
    return payload.array();
}

@Test
public void test(){
    byte[] packet = generateTestPacket();
    for(int i = 0; i < packet.length - 1; i++){
        parser.mavlink_parse_char(packet[i] & 0xFF);
    }
    MAVLinkPacket m = parser.mavlink_parse_char(packet[packet.length - 1] & 0xFF);
    byte[] processedPacket = m.encodePacket();
    assertArrayEquals("msg_led_control", processedPacket, packet);
}
}
        