/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */
         
// MESSAGE SAFETY_ALLOWED_AREA PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Parser;
import com.MAVLink.ardupilotmega.CRC;
import java.nio.ByteBuffer;
import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

/**
* Read out the safety zone the MAV currently assumes.
*/
public class msg_safety_allowed_area_test{

public static final int MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA = 55;
public static final int MAVLINK_MSG_LENGTH = 25;
private static final long serialVersionUID = MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA;

private Parser parser = new Parser();

public CRC generateCRC(byte[] packet){
    CRC crc = new CRC();
    for (int i = 1; i < packet.length - 2; i++) {
        crc.update_checksum(packet[i] & 0xFF);
    }
    crc.finish_checksum(MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA);
    return crc;
}

public byte[] generateTestPacket(){
    ByteBuffer payload = ByteBuffer.allocate(6 + MAVLINK_MSG_LENGTH + 2);
    payload.put((byte)MAVLinkPacket.MAVLINK_STX); //stx
    payload.put((byte)MAVLINK_MSG_LENGTH); //len
    payload.put((byte)0); //seq
    payload.put((byte)255); //sysid
    payload.put((byte)190); //comp id
    payload.put((byte)MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA); //msg id
    payload.putFloat((float)17.0); //p1x
    payload.putFloat((float)45.0); //p1y
    payload.putFloat((float)73.0); //p1z
    payload.putFloat((float)101.0); //p2x
    payload.putFloat((float)129.0); //p2y
    payload.putFloat((float)157.0); //p2z
    payload.put((byte)77); //frame
    
    CRC crc = generateCRC(payload.array());
    payload.put((byte)crc.getLSB());
    payload.put((byte)crc.getMSB());
    return payload.array();
}

@Test
public void test(){
    byte[] packet = generateTestPacket();
    for(int i = 0; i < packet.length - 1; i++){
        parser.mavlink_parse_char(packet[i] & 0xFF);
    }
    MAVLinkPacket m = parser.mavlink_parse_char(packet[packet.length - 1] & 0xFF);
    byte[] processedPacket = m.encodePacket();
    assertArrayEquals("msg_safety_allowed_area", processedPacket, packet);
}
}
        