/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */
         
// MESSAGE ATTITUDE_QUATERNION_COV PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Parser;
import com.MAVLink.ardupilotmega.CRC;
import java.nio.ByteBuffer;
import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

/**
* The attitude in the aeronautical frame (right-handed, Z-down, X-front, Y-right), expressed as quaternion. Quaternion order is w, x, y, z and a zero rotation would be expressed as (1 0 0 0).
*/
public class msg_attitude_quaternion_cov_test{

public static final int MAVLINK_MSG_ID_ATTITUDE_QUATERNION_COV = 61;
public static final int MAVLINK_MSG_LENGTH = 68;
private static final long serialVersionUID = MAVLINK_MSG_ID_ATTITUDE_QUATERNION_COV;

private Parser parser = new Parser();

public CRC generateCRC(byte[] packet){
    CRC crc = new CRC();
    for (int i = 1; i < packet.length - 2; i++) {
        crc.update_checksum(packet[i] & 0xFF);
    }
    crc.finish_checksum(MAVLINK_MSG_ID_ATTITUDE_QUATERNION_COV);
    return crc;
}

public byte[] generateTestPacket(){
    ByteBuffer payload = ByteBuffer.allocate(6 + MAVLINK_MSG_LENGTH + 2);
    payload.put((byte)MAVLinkPacket.MAVLINK_STX); //stx
    payload.put((byte)MAVLINK_MSG_LENGTH); //len
    payload.put((byte)0); //seq
    payload.put((byte)255); //sysid
    payload.put((byte)190); //comp id
    payload.put((byte)MAVLINK_MSG_ID_ATTITUDE_QUATERNION_COV); //msg id
    payload.putInt((int)963497464); //time_boot_ms
    //q
    payload.putFloat((float)45.0);
    payload.putFloat((float)46.0);
    payload.putFloat((float)47.0);
    payload.putFloat((float)48.0);
    payload.putFloat((float)157.0); //rollspeed
    payload.putFloat((float)185.0); //pitchspeed
    payload.putFloat((float)213.0); //yawspeed
    //covariance
    payload.putFloat((float)241.0);
    payload.putFloat((float)242.0);
    payload.putFloat((float)243.0);
    payload.putFloat((float)244.0);
    payload.putFloat((float)245.0);
    payload.putFloat((float)246.0);
    payload.putFloat((float)247.0);
    payload.putFloat((float)248.0);
    payload.putFloat((float)249.0);
    
    CRC crc = generateCRC(payload.array());
    payload.put((byte)crc.getLSB());
    payload.put((byte)crc.getMSB());
    return payload.array();
}

@Test
public void test(){
    byte[] packet = generateTestPacket();
    for(int i = 0; i < packet.length - 1; i++){
        parser.mavlink_parse_char(packet[i] & 0xFF);
    }
    MAVLinkPacket m = parser.mavlink_parse_char(packet[packet.length - 1] & 0xFF);
    byte[] processedPacket = m.encodePacket();
    assertArrayEquals("msg_attitude_quaternion_cov", processedPacket, packet);
}
}
        